stages:
  - sync-code
  - build
  - deploy

sync-code:
  stage: sync-code
  only:
    - master
  script:
    # - echo "$DOCKER_HUB_USER_NAME $DOCKER_HUB_USER_PASSWORD $QIUSHAO_HOME_GIT_RSA"
    - echo `ls /root`
  tags:
    - qiushaocloud-runner

build:
  stage: build
  only:
    - master
  script:
    - cd redis-cluster-image && sh build-docker.sh
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - cd redis-cluster-image && sh push-docker.sh
  tags:
    - qiushaocloud-runner
  