stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - cd redis-cluster-image && sh build-docker.sh
  tags:
    - qiushaocloud-runner

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login --username $DOCKER_HUB_USER_NAME --password $DOCKER_HUB_USER_PASSWORD
    - cd redis-cluster-image && sh push-docker.sh
  tags:
    - qiushaocloud-runner