version: '3'
services:
  redis-cluster-node-6373:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6373
    container_name: redis-cluster-node-6373
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6373:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6373
    ports:
      - 6373:6373
      - 16373:16373

  redis-cluster-node-6374:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6374
    container_name: redis-cluster-node-6374
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6374:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6374
    ports:
      - 6374:6374
      - 16374:16374

  redis-cluster-node-6375:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6375
    container_name: redis-cluster-node-6375
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6375:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6375
    ports:
      - 6375:6375
      - 16375:16375

  redis-cluster-node-6376:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6376
    container_name: redis-cluster-node-6376
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6376:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6376
    ports:
      - 6376:6376
      - 16376:16376

  redis-cluster-node-6377:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6377
    container_name: redis-cluster-node-6377
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6377:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6377
    ports:
      - 6377:6377
      - 16377:16377
  
  redis-cluster-node-6378:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-node-6378
    container_name: redis-cluster-node-6378
    volumes:
      - $STORAGES_DIR/redis-cluster-data-6378:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6378
    ports:
      - 6378:6378
      - 16378:16378

  redis-cluster-create:
    image: qiushaocloud/redis-cluster:latest
    #network_mode: host
    networks:
      - redis-cluster-network
    hostname: redis-cluster-create
    container_name: redis-cluster-create
    command: bash /run-create-cluster.sh
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=redis-cluster-node-6373:6373 redis-cluster-node-6374:6374 redis-cluster-node-6375:6375 redis-cluster-node-6376:6376 redis-cluster-node-6377:6377 redis-cluster-node-6378:6378
    depends_on:
      - redis-cluster-node-6373
      - redis-cluster-node-6374
      - redis-cluster-node-6375
      - redis-cluster-node-6376
      - redis-cluster-node-6377
      - redis-cluster-node-6378
    links:
      - redis-cluster-node-6373
      - redis-cluster-node-6374
      - redis-cluster-node-6375
      - redis-cluster-node-6376
      - redis-cluster-node-6377
      - redis-cluster-node-6378

networks:
  redis-cluster-network:
    driver: bridge


