version: '3'
services:
  cluster-redis-6373:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network-6373
    hostname: cluster-redis-6373
    container_name: cluster-redis-6373
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6373:/data
    ports:
      - 6373:6373
      - 16373:16373
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6373


networks:
  cluster-redis-network-6373:

