version: '3'
services:
  cluster-redis-6376:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network-6376
    hostname: cluster-redis-6376
    container_name: cluster-redis-6376
    volumes:
      - ./redis_confs/redis_6376.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6376:/data
      - ./hosts:/etc/hosts
    ports:
      - 6376:6376
      - 16376:16376


networks:
  cluster-redis-network-6376:

