version: '3'
services:
  cluster-redis-6377:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network-6377
    hostname: cluster-redis-6377
    container_name: cluster-redis-6377
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6377:/data
    ports:
      - 6377:6377
      - 16377:16377
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6377


networks:
  cluster-redis-network-6377:

