version: '3'
services:
  cluster-redis-6373:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network-6373
    hostname: cluster-redis-6373
    container_name: cluster-redis-6373
    volumes:
      - ./redis_confs/redis_6373.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6373:/data
      - ./hosts:/etc/hosts
    ports:
      - 6373:6373
      - 16373:16373


networks:
  cluster-redis-network-6373:

