version: '3'
services:
  cluster-redis-6373:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6373
    container_name: cluster-redis-6373
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6373:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6373

  cluster-redis-6374:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6374
    container_name: cluster-redis-6374
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6374:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6374

  cluster-redis-6375:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6375
    container_name: cluster-redis-6375
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6375:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6375

  cluster-redis-6376:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6376
    container_name: cluster-redis-6376
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6376:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6376

  cluster-redis-6377:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6377
    container_name: cluster-redis-6377
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6377:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6377
  
  cluster-redis-6378:
    image: redis
    command: bash /run-redis-server.sh # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6378
    container_name: cluster-redis-6378
    volumes:
      - ./run-redis-server.sh:/run-redis-server.sh
      - $STORAGES_DIR/redis-data-6378:/data
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6378


  cluster-redis-create:
    image: redis:latest
    network_mode: host
    hostname: cluster-redis-create
    container_name: cluster-redis-create
    command: bash /run-create-cluster.sh
    volumes:
      - ./run-create-cluster.sh:/run-create-cluster.sh
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=127.0.0.1:6373 127.0.0.1:6374 127.0.0.1:6375 127.0.0.1:6376 127.0.0.1:6377 127.0.0.1:6378
    depends_on:
      - cluster-redis-6373
      - cluster-redis-6374
      - cluster-redis-6375
      - cluster-redis-6376
      - cluster-redis-6377
      - cluster-redis-6378


