version: '3'
services:
  cluster-redis-6373:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network
    hostname: cluster-redis-6373
    container_name: cluster-redis-6373
    volumes:
      - ./redis_confs/redis_6373.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6373:/data
    ports:
      - 6373:6373
      - 16373:16373

  cluster-redis-6374:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network
    hostname: cluster-redis-6374
    container_name: cluster-redis-6374
    volumes:
      - ./redis_confs/redis_6374.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6374:/data
    ports:
      - 6374:6374
      - 16374:16374

  cluster-redis-6375:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    #network_mode: host
    networks:
      - cluster-redis-network
    hostname: cluster-redis-6375
    container_name: cluster-redis-6375
    volumes:
      - ./redis_confs/redis_6375.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6375:/data
    ports:
      - 6375:6375
      - 16375:16375


  cluster-redis-create:
    image: redis:latest
    #network_mode: host
    networks:
      - cluster-redis-network
    hostname: cluster-redis-create
    container_name: cluster-redis-create
    command: redis-cli -a $REDIS_PASSWORD --cluster create cluster-redis-6373:6373 cluster-redis-6374:6374 cluster-redis-6375:6375 --cluster-replicas 0  --cluster-yes
    depends_on:
      - cluster-redis-6373
      - cluster-redis-6374
      - cluster-redis-6375
    links:
      - cluster-redis-6373
      - cluster-redis-6374
      - cluster-redis-6375


networks:
  cluster-redis-network:
    driver: bridge

