version: '3'
services:
  cluster-redis-6373:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6373
    container_name: cluster-redis-6373
    volumes:
      - ./redis_confs/redis_6373.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6373:/data

  cluster-redis-6374:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6374
    container_name: cluster-redis-6374
    volumes:
      - ./redis_confs/redis_6374.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6374:/data

  cluster-redis-6375:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6375
    container_name: cluster-redis-6375
    volumes:
      - ./redis_confs/redis_6375.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6375:/data

  cluster-redis-6376:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6376
    container_name: cluster-redis-6376
    volumes:
      - ./redis_confs/redis_6376.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6376:/data

  cluster-redis-6377:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6377
    container_name: cluster-redis-6377
    volumes:
      - ./redis_confs/redis_6377.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6377:/data
  
  cluster-redis-6378:
    image: redis
    command: "redis-server /usr/local/etc/redis/redis.conf" # 覆盖容器启动后默认执行的命令
    restart: always
    network_mode: host
    hostname: cluster-redis-6378
    container_name: cluster-redis-6378
    volumes:
      - ./redis_confs/redis_6378.conf:/usr/local/etc/redis/redis.conf
      - $STORAGES_DIR/redis-data-6378:/data


  cluster-redis-create:
    image: redis:latest
    network_mode: host
    hostname: cluster-redis-create
    container_name: cluster-redis-create
    command: bash /run-create-cluster.sh
    volumes:
      - ./run-create-cluster.sh:/run-create-cluster.sh
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_NODES=127.0.0.1:6373 127.0.0.1:6374 127.0.0.1:6375 127.0.0.1:6376 127.0.0.1:6377 127.0.0.1:6378
    depends_on:
      - cluster-redis-6373
      - cluster-redis-6374
      - cluster-redis-6375
      - cluster-redis-6376
      - cluster-redis-6377
      - cluster-redis-6378


