version: '3'
services:
  redis-cluster-node-6378:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6378
    hostname: redis-cluster-node-6378
    container_name: redis-cluster-node-6378
    volumes:
      - $STORAGES_DIR/redis-data-6378:/data
    ports:
      - 6378:6378
      - 16378:16378
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6378


networks:
  redis-cluster-network-6378:

