version: '3'
services:
  redis-cluster-node-6377:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6377
    hostname: redis-cluster-node-6377
    container_name: redis-cluster-node-6377
    volumes:
      - $STORAGES_DIR/redis-data-6377:/data
    ports:
      - 6377:6377
      - 16377:16377
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6377


networks:
  redis-cluster-network-6377:

