version: '3'
services:
  redis-cluster-node-6375:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6375
    hostname: redis-cluster-node-6375
    container_name: redis-cluster-node-6375
    volumes:
      - $STORAGES_DIR/redis-data-6375:/data
    ports:
      - 6375:6375
      - 16375:16375
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6375


networks:
  redis-cluster-network-6375:

