version: '3'
services:
  redis-cluster-node-6374:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6374
    hostname: redis-cluster-node-6374
    container_name: redis-cluster-node-6374
    volumes:
      - $STORAGES_DIR/redis-data-6374:/data
    ports:
      - 6374:6374
      - 16374:16374
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6374


networks:
  redis-cluster-network-6374:

