version: '3'
services:
  redis-cluster-node-6376:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6376
    hostname: redis-cluster-node-6376
    container_name: redis-cluster-node-6376
    volumes:
      - $STORAGES_DIR/redis-data-6376:/data
    ports:
      - 6376:6376
      - 16376:16376
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6376


networks:
  redis-cluster-network-6376:

