version: '3'
services:
  redis-cluster-node-6373:
    image: qiushaocloud/redis-cluster:latest
    restart: always
    #network_mode: host
    networks:
      - redis-cluster-network-6373
    hostname: redis-cluster-node-6373
    container_name: redis-cluster-node-6373
    volumes:
      - $STORAGES_DIR/redis-data-6373:/data
    ports:
      - 6373:6373
      - 16373:16373
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_CLUSTER_ANNOUNCE_IP=$REDIS_CLUSTER_ANNOUNCE_IP
      - REDIS_PORT_NUMBER=6373


networks:
  redis-cluster-network-6373:

